// REALIZAR API REST CON LOS SIGUIENTES ENDPOINT
// 1-API/FRASE QUE DEVUELVA UNA FRASE EN UN CAMPO "FRASE"
// 2-API/LETRAS/:NUM - DEVUELVE POR NUMERO DE ORDEN LA LETRA DENTRO DE FRASE, EN UN CAMPO "LETRA"
// 3-API/PALABRAS/:NUM - DEVUELVE POR NUMERO DE ORDEN LA PALABRA DENTRO DE ESA FRASE, EN UN CAMPO "PALABRA"

// DEBE HACER CONTROL DE SI EL NUMERO ES NUMERICO O NO Y SI ESTA POR FUERA DEL RANGO DE LETRAS O PALABRAS SINO DEBERA MOSTRAR ERROR

// { error: "El parametro no es un numero"}
// {error: "El parametro esta fuera de rango"} cuando no esta entre 1 y el total de letras/palabras
